using System.Diagnostics.CodeAnalysis;

namespace DiscordBibleBot.Source.Roles;

public static class MyRoles
{
    public static readonly Role Demon = new() {Name = "Cute Demon", Reason = "Autogenerated for cult bot."};
    public static readonly Role Cultist = new() {Name = "Cultist", Reason = "Autogenerated for cult bot."};
    public static readonly Role Sacrificed = new() {Name = "Sacrificed", Reason = "Autogenerated for cult bot."};
    
    /// <summary>
    /// A string over all roles in the class.
    /// </summary>
    public static readonly Role[] Enumerable = {Demon, Cultist, Sacrificed};

    /// <summary>
    /// Gets the role from it's name.
    /// </summary>
    /// <param name="roleName">The name of the role to get the id of.</param>
    /// <param name="matchRole">The id. null if no role with the name could be found.</param>
    /// <returns>true, if the identifier is found, else false.</returns>
    public static bool TryGetRole(
        string roleName,
        [MaybeNullWhen(false)] out Role? matchRole)
    {
        string nameLow = roleName.ToLower();
        foreach (var role in Enumerable)
        {
            if (role.Name.ToLower() != nameLow) continue;
            matchRole = role;
            return true;
        }

        matchRole = default;
        return false;
    }
}